# Travis CI configuration file for WordPress Helpers
language: php
dist: trusty
sudo: false

branches:
  only:
    - master
    - /^issue\/\d+\.\d+(\.\d+)?(-\S*)?$/
    - /^feature\/*/

# Additional tests against stable PHP (min recommended version is 5.6) and past supported versions of WP
# and code coverage report.
matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0 COVERAGE=1
    - php: 7.2
      env: WP_VERSION=latest WP_MULTISITE=1 PHPLINT=1 PHPCS=1 TRAVIS_NODE_VERSION=node
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=4.8
    - php: 7.2
      env: WP_VERSION=4.7.5
    - php: 7.2
      env: WP_VERSION=4.6
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
  allow_failures:
    - env: WP_VERSION=latest WP_MULTISITE=1 PHPLINT=1 PHPCS=1 TRAVIS_NODE_VERSION=node

cache:
  directories:
    - node_modules
    - $HOME/.composer/cache
    - vendor

before_install:
  - if [[ -z "$CC_TEST_REPORTER_ID" ]]; then COVERAGE="0"; fi
  - if [[ "$COVERAGE" != "1" ]]; then phpenv config-rm xdebug.ini || echo 'No xdebug config.'; fi

install:
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" || $TRAVIS_PHP_VERSION == "nightly" ]]; then composer require --dev phpunit/phpunit ^5.7; fi
  - composer install -o --prefer-dist --no-interaction
  - composer global require "phpunit/phpunit=4.8.*|5.7.*"

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - export -f travis_nanoseconds
  - export -f travis_fold
  - export -f travis_time_start
  - export -f travis_time_finish
  - bash tests/bin/install.sh wordpress_test root '' localhost $WP_VERSION
  - bash tests/bin/travis.sh before

script:
  - bash tests/bin/phplint.sh
  - bash tests/bin/phpunit.sh
  - bash tests/bin/phpcs.sh

after_script:
  - bash tests/bin/travis.sh after

notifications:
  email: false
